### ISSUE TITLE
Allow user analyze all bundles

### ISSUE THREAD

**Issue by DmitryEfimenko** [ngx-builders/source-map-analyzer#41]
Currently, there's a selector that asks which bundle needs to be analyzed. Usually, I prefer to analyze all bundles at the same time since this gives me a good big picture. From there I can always drill down. I achieve it by using the following command:
```
source-map-explorer dist/web/*es2015.js
```
I think the very first option in the list of bundles should be exactly that: `*es2015.js`

What do you think?

**Comment by santoshyadav198613** [comment]
Yes sound great, Would you like to open a PR 😊.
