### ISSUE TITLE
source-map-explorer: command not found

### ISSUE THREAD

**Issue by DanWahlin** [ngx-builders/source-map-analyzer#5]
Thanks for putting this together! I tried it out today but got the following error after running `ng run code-labs:analyze` on an Angular 9 project:

```
Command failed: source-map-explorer dist/code-labs/main-es2015.833680ea182f4b5c80ef.js
/bin/sh: source-map-explorer: command not found
```

I do see the `source-map-explorer` package in `package.json` and my `angular.json` file has what appears to be the proper updates for the builder. Anything else I need to do?

**Comment by santoshyadav198613** [comment]
Thanks for trying it @DanWahlin I will get it checked.

**Comment by santoshyadav198613** [comment]
Thanks for the issue @DanWahlin realized fo this version we need source-map-explorer to be installed globally, updated the doc, but I will keep this open as a feature request. 
Will avoid this dependency for the next major release.

**Comment by DanWahlin** [comment]
Good deal - that works great. Thanks again for putting this together!
