### ISSUE TITLE
Command failed: npx source-map-explorer dist/

### ISSUE THREAD

**Issue by iamsurajdc** [ngx-builders/source-map-analyzer#53]
I'm getting this error even if I followed the docs properly, Is there anything I am doing wrong ?

`**Command failed: npx source-map-explorer dist/doewebreport/*es2015.*.js
npx: installed 66 in 17.446s**`

![Annotation 2020-10-11 142419](https://user-images.githubusercontent.com/32074031/95674392-928f5400-0bcd-11eb-8014-04fba6c8ceee.png)

**Comment by iamsurajdc** [comment]
@santoshyadavdev

**Comment by Parsa-Sedigh** [comment]
Same error here. I'm using angular CLI 10.1.0

**Comment by santoshyadavdev** [comment]
@iamsurajdc  @Parsa-Sedigh  Sorry for the late reply, for Angular 10 projects you need to set diffLoading=false
