### ISSUE TITLE
Its not working in Angular 11 projects

### ISSUE THREAD

**Issue by maniya108** [ngx-builders/source-map-analyzer#59]
My application was created in angular 11 and i installed this plugin. But it show the below error.
![image](https://user-images.githubusercontent.com/62015493/100696523-c27efa80-33b9-11eb-88a9-5032b156b4b4.png)

**Comment by santoshyadavdev** [comment]
Ohh can you try with diffLoading: false in options

**Comment by sekoch** [comment]
I had the same problem. With `--diffLoading=false` as @santoshyadavdev suggested, it works in Angular v11 projects.

**Comment by Dimanoid** [comment]
Same problem and with `--diffLoading=false` option I have tthe following output and nothing more...

```
Build at: 2021-01-29T17:49:49.285Z - Hash: c2cefc16c40c2ef4ed5d - Time: 39817ms
dist/web/4.27b902caa15c2fb91369.js
dist/web/5.c96fcef6d999959167c7.js
dist/web/main.5676fb550d74f556e78a.js
dist/web/polyfills.bb555cde732bc3ec9fae.js
dist/web/runtime.a0b6b2592075c329b67e.js

  Unable to map 217/172229 bytes (0.13%)
  Unable to map 189/703 bytes (26.88%)
  Unable to map 93/613519 bytes (0.02%)
  Unable to map 117/37322 bytes (0.31%)
  Unable to map 13/2360 bytes (0.55%)```

**Comment by santoshyadavdev** [comment]
> Same problem and with `--diffLoading=false` option I have tthe following output and nothing more...
> 
> ```
> Build at: 2021-01-29T17:49:49.285Z - Hash: c2cefc16c40c2ef4ed5d - Time: 39817ms
> dist/web/4.27b902caa15c2fb91369.js
> dist/web/5.c96fcef6d999959167c7.js
> dist/web/main.5676fb550d74f556e78a.js
> dist/web/polyfills.bb555cde732bc3ec9fae.js
> dist/web/runtime.a0b6b2592075c329b67e.js
> 
>   Unable to map 217/172229 bytes (0.13%)
>   Unable to map 189/703 bytes (26.88%)
>   Unable to map 93/613519 bytes (0.02%)
>   Unable to map 117/37322 bytes (0.31%)
>   Unable to map 13/2360 bytes (0.55%)```
> ```

It may happen to rights issue too, can you try running command prompt with admin rights
