### ISSUE TITLE
Command failed: npx source-map-explorer dist/*es2015.*.js

### ISSUE THREAD

**Issue by gradzio** [ngx-builders/source-map-analyzer#73]
Just running analyzer on my project and cannot get through.

When running `npx source-map-explorer dist/*es2015.*.js` I do not seem to get any errors (maybe silent?)

I do not seem to be getting any log or comprehensive message, so let me know if I need to provide anything else.

Setup: Linux Ubuntu, npm 6.14.12, node v14.16.1, Angular 11.2, @ngx-builders/analyze 2.3.0

**Comment by santoshyadavdev** [comment]
Try setting the diffloading to false https://github.com/ngx-builders/source-map-analyzer#--diffloading-
